import {speakerLibrary,assignmentTargets} from '../desktop/people.mjs';
import {_electron as electron} from '/Users/rafael/Documents/Codex/2026-09-06/any-x20/atlas/node_modules/@playwright/test/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile,copyFile} from 'node:fs/promises';
const records=[{job:{id:'a',sha256:'same',title:'a',languages:['English']},transcript:{segments:[{start:0,end:5,text:'test'}]},labels:[{index:0,name:'Old',start:0,end:5},{index:0,name:'Correct',start:0,end:5}]},{job:{id:'b',sha256:'same',title:'b',languages:['English']},transcript:{segments:[{start:2,end:7,text:'test'}]},labels:[{index:0,name:'Correct',start:2,end:7}]}];
const library=speakerLibrary(records,{profiles:{}});assert.equal(library.length,1);assert.equal(library[0].name,'Correct');assert.equal(library[0].recordingCount,1);assert.equal(library[0].seconds,7);assert.equal(library[0].segmentCount,2);assert.equal(library[0].exampleCount,0);
assert.deepEqual(assignmentTargets([{speaker:'SPEAKER_00'},{speaker:'SPEAKER_00'},{speaker:'SPEAKER_00'},{speaker:'UNASSIGNED'}],[{index:2,name:'Keep'}],0,true),[0,1]);
assert.deepEqual(assignmentTargets([{speaker:'UNASSIGNED'},{speaker:'UNASSIGNED'}],[],0,true),[0]);
assert.deepEqual(assignmentTargets([{speaker:'SPEAKER_00'},{speaker:'SPEAKER_00'}],[],0,false),[0]);
const root='/Users/rafael/Documents/Codex/2026-09-07/tra';
const data=root+'/work/ui-test-data';await mkdir(data+'/test-one',{recursive:true});await mkdir(data+'/scripts',{recursive:true});await writeFile(data+'/scripts/correction-memory.json',JSON.stringify({vocabulary:[],corrections:[]}));
await copyFile(root+'/work/recording.wav',data+'/test-one/audio.wav');
const job={id:'test-one',title:'Teste de revisão.m4a',status:'done',phase:'Pronta para revisar',audio:data+'/test-one/audio.wav',createdAt:new Date().toISOString(),speakers:2,languages:['Portuguese','English']};
await writeFile(data+'/queue.json',JSON.stringify({paused:true,jobs:[job]}));
await writeFile(data+'/test-one/transcript.json',JSON.stringify({segments:[{start:0,end:5,speaker:'SPEAKER_00',text:'Texto original de teste.'},{start:6,end:6.2,speaker:'SPEAKER_01',text:'Second speaker, switching languages.'},{start:8,end:12,speaker:'SPEAKER_00',text:'Outra fala da primeira voz.'}],asr:{text:'original'},diarization:{num_speakers:2}}));
await writeFile(data+'/test-one/labels.json','[]');
const app=await electron.launch({executablePath:'/Users/rafael/Documents/Codex/2026-09-06/any-x20/atlas/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',args:[root+'/outputs/fita'],env:{...process.env,FITA_DATA:data,FITA_SCRIPTS:data+'/scripts'}});
try{
const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.locator('.record').waitFor();await page.screenshot({path:root+'/work/ui-initial.png'});
await page.locator('.record').click();await page.locator('.segment').first().waitFor();
await page.locator('[data-edit="0"]').click();await page.locator('#edit-form textarea').fill('Correção confirmada.');await page.locator('#edit-form [type=submit]').click();
await page.waitForFunction(()=>document.querySelector('.segment p')?.textContent==='Correção confirmada.');
assert.equal(JSON.parse(await readFile(data+'/test-one/transcript.json')).segments[0].text,'Texto original de teste.');
assert.equal(JSON.parse(await readFile(data+'/test-one/edits.json'))[0].text,'Correção confirmada.');
const libraryBefore=await readFile(data+'/scripts/voice-library.json','utf8').catch(()=>null);
await page.locator('.speaker-select[data-assign="1"]').click();assert.equal(await page.locator('#assign-group-label').isVisible(),false);assert.equal(await page.locator('#assign-learn-label').isVisible(),false);await page.locator('#assign-form [name=person]').fill('Pessoa de teste');await page.locator('#assign-form [type=submit]').click();
await page.waitForFunction(()=>document.querySelectorAll('.speaker')[1]?.textContent.includes('Pessoa de teste'));
await page.locator('.speaker-select[data-assign="1"]').click();await page.locator('#assign-form [name=person]').fill('Nome corrigido');await page.locator('#assign-form [type=submit]').click();
await page.waitForFunction(()=>document.querySelectorAll('.speaker')[1]?.textContent.includes('Nome corrigido'));
assert.equal(await readFile(data+'/scripts/voice-library.json','utf8').catch(()=>null),libraryBefore);
await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file})},data+'/assigned-export.json');
await page.locator('[data-export=json]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('exportada'));
assert.equal(JSON.parse(await readFile(data+'/assigned-export.json')).segments[1].speaker,'Nome corrigido');
assert.equal(JSON.parse(await readFile(data+'/test-one/transcript.json')).segments[1].speaker,'SPEAKER_01');
await page.locator('[data-voice="0"]').click();assert.equal(await page.locator('#voice-form [name=start]').inputValue(),'0.0');await page.keyboard.press('Escape');
await page.locator('[data-action=reviewed]').click();await page.waitForFunction(()=>document.querySelector('[data-action=reviewed]').textContent==='Reabrir revisão');
await page.locator('nav [data-view=people]').click();await page.getByRole('heading',{name:'Nome corrigido',exact:true}).waitFor();assert.equal(await page.locator('.person-card').count(),1);await page.getByText('Pessoa cadastrada pelas atribuições.',{exact:false}).waitFor();
await page.locator('[data-view=settings]').click();const wasQuiet=await page.locator('body').evaluate(el=>el.classList.contains('quiet'));await page.locator('#aura-toggle').click();assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('quiet')),!wasQuiet);
await page.locator('nav [data-view=recordings]').click();await page.keyboard.press('/');assert.equal(await page.locator('#search').evaluate(el=>el===document.activeElement),true);
await page.locator('#search').fill('inexistente');assert.equal(await page.locator('.record').count(),0);await page.locator('#search').fill('');await page.locator('.record').waitFor();
await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},root+'/outputs/fita/data/weser-187/original.m4a');
await page.locator('#import').click();await page.waitForFunction(()=>document.querySelectorAll('.record').length===2);await page.locator('#import').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('repetida'));assert.equal(await page.locator('.record').count(),2);
await page.locator('.record').filter({hasText:'Teste de revisão'}).click();
await page.locator('.speaker-select[data-assign="0"]').click();assert.equal(await page.locator('#assign-form [name=group]').isChecked(),true);await page.locator('#assign-form [name=person]').fill('Grupo confirmado');await page.locator('#assign-form [type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.speaker')[2]?.textContent.includes('Grupo confirmado'));const grouped=JSON.parse(await readFile(data+'/test-one/labels.json'));assert.equal(grouped.filter(l=>l.name==='Grupo confirmado').length,2);assert.equal(await readFile(data+'/scripts/voice-library.json','utf8').catch(()=>null),libraryBefore);
await page.locator('[data-action=retranscribe]').click();
await page.waitForFunction(()=>document.querySelector('h1')?.textContent.includes('nova versão'));
const after=JSON.parse(await readFile(data+'/queue.json'));const newer=after.jobs.find(j=>j.sourceJob==='test-one');assert.ok(newer);assert.equal(newer.model,'mlx-community/whisper-large-v3-mlx');assert.equal(newer.status,'queued');assert.equal(JSON.parse(await readFile(data+'/test-one/edits.json'))[0].text,'Correção confirmada.');
assert.equal(await page.evaluate(()=>typeof window.require),'undefined');assert.deepEqual(errors,[]);
console.log('PASS: import-ready list, review, preserved original, corrections, voice confirmation UI, reviewed state, navigation, search, appearance, renderer isolation.');
}finally{await app.close()}
